import {
  getAlbum,
  getAlbumDynamic,
  getAlbumList,
  getAlbumPrivileges,
  getAlbumProduct,
  getAlbumSaleBoard,
  getNewestAlbums,
} from "./apis/album";
import {
  getArtist,
  getArtistAlbums,
  getArtistDesc,
  getArtistDetail,
  getArtistList,
  getArtistMvs,
  getArtistSongs,
  getArtistTopSongs,
  getArtistVideos,
} from "./apis/artist";
import {
  getHighQualityPlaylists,
  getHighQualityTags,
  getPlaylistCategories,
  getPlaylistDetail,
  getPlaylistDetailDynamic,
  getPlaylistTracks,
  getRelatedPlaylists,
  getTopPlaylists,
} from "./apis/playlist";
import {
  checkMusic,
  getLyric,
  getLyricNew,
  getSimilarSongs,
  getSongUrl,
  getSongsDetail,
} from "./apis/song";
import {
  cloudSearch,
  getDefaultSearchKeyword,
  getHotSearchDetail,
  getHotSearches,
  getSearchSuggest,
  search,
  searchMultimatch,
} from "./apis/search";

export type {
  Album,
  AlbumRef,
  Artist,
  ArtistRef,
  MvRef,
  PlaylistSummary,
  Song,
  SongUrl,
  UserRef,
  VideoRef,
} from "./types/common";
export type {
  HotSearchGroup,
  HotSearchItem,
  SearchLyric,
  SearchRadio,
  SearchResult,
  SearchSuggest,
  SearchType,
} from "./types/search";
export type { Lyric, LyricLine, LyricNew, WordLine } from "./types/Lyric";
export type { MusicAvailability, SongDetail } from "./types/SongDetails";
export type {
  PlaylistCategory,
  PlaylistDetail,
  PlaylistPage,
  PlaylistStats,
  PlaylistTag,
} from "./types/PlaylistDetail";
export type {
  AlbumPage,
  AlbumPrivilege,
  AlbumProduct,
  AlbumSaleBoard,
  AlbumStats,
} from "./types/album";
export type {
  ArtistDescription,
  ArtistPage,
  ArtistVideoPage,
} from "./types/artist";
export type * from "./types/params";

export { NeteaseApiError } from "./errors";
export { request } from "./client";
export type { Crypto, RequestOptions } from "./client";

export {
  search,
  cloudSearch,
  getSearchSuggest,
  getHotSearches,
  getHotSearchDetail,
  getDefaultSearchKeyword,
  searchMultimatch,
  getSongsDetail,
  getSongUrl,
  getLyric,
  getLyricNew,
  checkMusic,
  getSimilarSongs,
  getPlaylistDetail,
  getPlaylistTracks,
  getPlaylistDetailDynamic,
  getHighQualityTags,
  getTopPlaylists,
  getHighQualityPlaylists,
  getPlaylistCategories,
  getRelatedPlaylists,
  getArtist,
  getArtistDetail,
  getArtistSongs,
  getArtistTopSongs,
  getArtistAlbums,
  getArtistList,
  getArtistDesc,
  getArtistMvs,
  getArtistVideos,
  getAlbum,
  getAlbumProduct,
  getAlbumDynamic,
  getAlbumSaleBoard,
  getAlbumPrivileges,
  getAlbumList,
  getNewestAlbums,
};

export default {
  search,
  cloudSearch,
  getSearchSuggest,
  getHotSearches,
  getHotSearchDetail,
  getDefaultSearchKeyword,
  searchMultimatch,
  getSongsDetail,
  getSongUrl,
  getLyric,
  getLyricNew,
  checkMusic,
  getSimilarSongs,
  getPlaylistDetail,
  getPlaylistTracks,
  getPlaylistDetailDynamic,
  getHighQualityTags,
  getTopPlaylists,
  getHighQualityPlaylists,
  getPlaylistCategories,
  getRelatedPlaylists,
  getArtist,
  getArtistDetail,
  getArtistSongs,
  getArtistTopSongs,
  getArtistAlbums,
  getArtistList,
  getArtistDesc,
  getArtistMvs,
  getArtistVideos,
  getAlbum,
  getAlbumProduct,
  getAlbumDynamic,
  getAlbumSaleBoard,
  getAlbumPrivileges,
  getAlbumList,
  getNewestAlbums,
};
